version: "3.8"

services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.local

  backend:
    build: ./backend
    ports:
      - "3001:3001"

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bank"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
