name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs: 
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      -name: Check out Repo
      uses: actions/checkout@v4

      -name: Copy files to EC2 
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "."
        target: "/home/ubuntu/?"

      -name: Run Docker on EC2 
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: 
          cd/home/ubuntu/docker-github-actions
          sudo docker compose down
          sudo docker compose up -d --build